// This file is auto-generated. To include assets for the lazyloader, just add your .js file to Assets/js/blocks/ and it will be included here.
const dynamicAssets = [
  { assetKey: "theme-switcher" },
  { assetKey: "tabbed-content-v2" },
  { assetKey: "sub-tabbed-content" },
  { assetKey: "sub-group-container" },
  { assetKey: "sticky-link" },
  { assetKey: "standard-content-v2" },
  { assetKey: "spacer-v2" },
  { assetKey: "slide-in-panel" },
  { assetKey: "site-title-and-tagline" },
  { assetKey: "site-logo-container" },
  { assetKey: "site-copyright-notice" },
  { assetKey: "single-video" },
  { assetKey: "single-responsive-image" },
  { assetKey: "single-lottie" },
  { assetKey: "single-content-box" },
  { assetKey: "single-column-container" },
  { assetKey: "section-separator" },
  { assetKey: "responsive-table" },
  { assetKey: "responsive-image" },
  { assetKey: "post-type-scroller" },
  { assetKey: "post-type-filter-grid-v2" },
  { assetKey: "post-info" },
  { assetKey: "personalised-links" },
  { assetKey: "nav-menu-container" },
  { assetKey: "mikmak-wtb" },
  { assetKey: "menu-presentation" },
  { assetKey: "market-selector" },
  { assetKey: "map-container" },
  { assetKey: "list-builder" },
  { assetKey: "iframe-container" },
  { assetKey: "group-container" },
  { assetKey: "gradient-layer" },
  { assetKey: "floating-links" },
  { assetKey: "event-details-banner" },
  { assetKey: "divider" },
  { assetKey: "debrain-wtb" },
  { assetKey: "debrain-label-shop" },
  { assetKey: "current-post-info" },
  { assetKey: "css-test" },
  { assetKey: "collection-carousel" },
  { assetKey: "carousel-thumbnail-gallery" },
  { assetKey: "carousel-multi-layout-v2" },
  { assetKey: "card-carousel-v2" },
  { assetKey: "breadcrumb-display" },
  { assetKey: "betterreviews-display" },
  { assetKey: "bazaarvoice-display" },
  { assetKey: "bambuser-display" },
  { assetKey: "back-to-top-button" },
  { assetKey: "animated-sections" },
  { assetKey: "airtable-dashboard" },
];
const api = {
  dynamicAssets,
};
export default api;
